name: resolvair
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  easy_debounce: ^2.0.3
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^13.0.2
  get_it: ^7.6.4
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.0
  mocktail: ^1.0.1
  multiple_result: ^5.1.0
  permission_handler: ^11.0.1
  osm_nominatim: ^3.0.0
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  syncfusion_flutter_gauges: 27.2.4
  url_launcher: ^6.1.14
  badges: ^3.1.2
  email_validator: ^3.0.0
  easy_localization: ^3.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  stacked_generator: ^1.3.3
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - ./assets/
    - assets/translations/
